2024-03-09 09:17:51,561 [ERROR] django.request: Internal Server Error: /admin/shopapp/product/
Traceback (most recent call last):
  File "/home/aa_lozovoy/PycharmProjects/pythonProject/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aa_lozovoy/PycharmProjects/pythonProject/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/aa_lozovoy/PycharmProjects/pythonProject/.venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "/home/aa_lozovoy/PycharmProjects/pythonProject/.venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/aa_lozovoy/PycharmProjects/pythonProject/.venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 75, in rendered_content
    return real_rendered_content.fget(self)
  File "/home/aa_lozovoy/PycharmProjects/pythonProject/.venv/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/aa_lozovoy/PycharmProjects/pythonProject/.venv/lib/python3.10/site-packages/django/template/response.py", line 74, in resolve_template
    return get_template(template, using=self.using)
  File "/home/aa_lozovoy/PycharmProjects/pythonProject/.venv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: shopapp/products_changelist.html
